export const weatherAPI = {
  "location": {
    "name": "Pune",
    "region": "Maharashtra",
    "country": "India",
    "lat": 18.5333,
    "lon": 73.8667,
    "tz_id": "Asia/Kolkata",
    "localtime_epoch": 1770284297,
    "localtime": "2026-02-05 15:08"
  },
  "current": {
    "last_updated_epoch": 1770283800,
    "last_updated": "2026-02-05 15:00",
    "temp_c": 30.8,
    "temp_f": 87.5,
    "is_day": 1,
    "condition": {
      "text": "Sunny",
      "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
      "code": 1000
    },
    "wind_mph": 5.8,
    "wind_kph": 9.4,
    "wind_degree": 91,
    "wind_dir": "E",
    "pressure_mb": 1013,
    "pressure_in": 29.91,
    "precip_mm": 0,
    "precip_in": 0,
    "humidity": 23,
    "cloud": 16,
    "feelslike_c": 29,
    "feelslike_f": 84.1,
    "windchill_c": 30.9,
    "windchill_f": 87.5,
    "heatindex_c": 29,
    "heatindex_f": 84.1,
    "dewpoint_c": 7.3,
    "dewpoint_f": 45.1,
    "vis_km": 10,
    "vis_miles": 6,
    "uv": 3.1,
    "gust_mph": 6.7,
    "gust_kph": 10.8,
    "short_rad": 0,
    "diff_rad": 0,
    "dni": 0,
    "gti": 0
  },
  "forecast": {
    "forecastday": [
      {
        "date": "2026-02-05",
        "date_epoch": 1770249600,
        "day": {
          "maxtemp_c": 30.9,
          "maxtemp_f": 87.6,
          "mintemp_c": 19,
          "mintemp_f": 66.2,
          "avgtemp_c": 25,
          "avgtemp_f": 77,
          "maxwind_mph": 12.8,
          "maxwind_kph": 20.5,
          "totalprecip_mm": 0,
          "totalprecip_in": 0,
          "totalsnow_cm": 0,
          "avgvis_km": 10,
          "avgvis_miles": 6,
          "avghumidity": 33,
          "daily_will_it_rain": 0,
          "daily_chance_of_rain": 0,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Sunny",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
            "code": 1000
          },
          "uv": 1.8
        },
        "astro": {
          "sunrise": "07:07 AM",
          "sunset": "06:30 PM",
          "moonrise": "09:46 PM",
          "moonset": "09:19 AM",
          "moon_phase": "Waning Gibbous",
          "moon_illumination": 89,
          "is_moon_up": 1,
          "is_sun_up": 0
        },
        "hour": [
          {
            "time_epoch": 1770229800,
            "time": "2026-02-05 00:00",
            "temp_c": 23,
            "temp_f": 73.4,
            "is_day": 0,
            "condition": {
              "text": "Clear ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.1,
            "wind_kph": 5,
            "wind_degree": 6,
            "wind_dir": "N",
            "pressure_mb": 1016,
            "pressure_in": 29.99,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 35,
            "cloud": 13,
            "feelslike_c": 24,
            "feelslike_f": 75.2,
            "windchill_c": 23,
            "windchill_f": 73.3,
            "heatindex_c": 24,
            "heatindex_f": 75.2,
            "dewpoint_c": 6.7,
            "dewpoint_f": 44,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6,
            "gust_kph": 9.6,
            "uv": 0,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1770233400,
            "time": "2026-02-05 01:00",
            "temp_c": 21.8,
            "temp_f": 71.2,
            "is_day": 0,
            "condition": {
              "text": "Clear ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 2,
            "wind_kph": 3.2,
            "wind_degree": 21,
            "wind_dir": "NNE",
            "pressure_mb": 1015,
            "pressure_in": 29.98,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 37,
            "cloud": 16,
            "feelslike_c": 21.8,
            "feelslike_f": 71.2,
            "windchill_c": 21.8,
            "windchill_f": 71.2,
            "heatindex_c": 23.8,
            "heatindex_f": 74.8,
            "dewpoint_c": 6.4,
            "dewpoint_f": 43.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 4.2,
            "gust_kph": 6.8,
            "uv": 0,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1770237000,
            "time": "2026-02-05 02:00",
            "temp_c": 20.6,
            "temp_f": 69.1,
            "is_day": 0,
            "condition": {
              "text": "Clear ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 2,
            "wind_kph": 3.2,
            "wind_degree": 35,
            "wind_dir": "NE",
            "pressure_mb": 1015,
            "pressure_in": 29.96,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 39,
            "cloud": 20,
            "feelslike_c": 20.6,
            "feelslike_f": 69.1,
            "windchill_c": 20.6,
            "windchill_f": 69.1,
            "heatindex_c": 20.6,
            "heatindex_f": 69.1,
            "dewpoint_c": 6.2,
            "dewpoint_f": 43.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 4.2,
            "gust_kph": 6.8,
            "uv": 0,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1770240600,
            "time": "2026-02-05 03:00",
            "temp_c": 20.3,
            "temp_f": 68.6,
            "is_day": 0,
            "condition": {
              "text": "Clear ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 2.5,
            "wind_kph": 4,
            "wind_degree": 80,
            "wind_dir": "E",
            "pressure_mb": 1014,
            "pressure_in": 29.95,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 39,
            "cloud": 20,
            "feelslike_c": 20.3,
            "feelslike_f": 68.6,
            "windchill_c": 20.3,
            "windchill_f": 68.6,
            "heatindex_c": 20.3,
            "heatindex_f": 68.6,
            "dewpoint_c": 6,
            "dewpoint_f": 42.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5.2,
            "gust_kph": 8.3,
            "uv": 0,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1770244200,
            "time": "2026-02-05 04:00",
            "temp_c": 19.9,
            "temp_f": 67.8,
            "is_day": 0,
            "condition": {
              "text": "Clear ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.4,
            "wind_kph": 5.4,
            "wind_degree": 67,
            "wind_dir": "ENE",
            "pressure_mb": 1014,
            "pressure_in": 29.95,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 40,
            "cloud": 18,
            "feelslike_c": 19.9,
            "feelslike_f": 67.8,
            "windchill_c": 19.9,
            "windchill_f": 67.8,
            "heatindex_c": 19.9,
            "heatindex_f": 67.8,
            "dewpoint_c": 5.9,
            "dewpoint_f": 42.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 7,
            "gust_kph": 11.3,
            "uv": 0,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1770247800,
            "time": "2026-02-05 05:00",
            "temp_c": 19.5,
            "temp_f": 67.1,
            "is_day": 0,
            "condition": {
              "text": "Clear ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 5.1,
            "wind_kph": 8.3,
            "wind_degree": 63,
            "wind_dir": "ENE",
            "pressure_mb": 1015,
            "pressure_in": 29.98,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 41,
            "cloud": 15,
            "feelslike_c": 19.5,
            "feelslike_f": 67.1,
            "windchill_c": 19.5,
            "windchill_f": 67.1,
            "heatindex_c": 19.5,
            "heatindex_f": 67.1,
            "dewpoint_c": 5.9,
            "dewpoint_f": 42.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.8,
            "gust_kph": 17.4,
            "uv": 0,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1770251400,
            "time": "2026-02-05 06:00",
            "temp_c": 19,
            "temp_f": 66.2,
            "is_day": 0,
            "condition": {
              "text": "Clear ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 4.7,
            "wind_kph": 7.6,
            "wind_degree": 77,
            "wind_dir": "ENE",
            "pressure_mb": 1016,
            "pressure_in": 30,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 42,
            "cloud": 11,
            "feelslike_c": 19,
            "feelslike_f": 66.2,
            "windchill_c": 19,
            "windchill_f": 66.2,
            "heatindex_c": 19,
            "heatindex_f": 66.2,
            "dewpoint_c": 5.9,
            "dewpoint_f": 42.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.9,
            "gust_kph": 15.9,
            "uv": 0,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1770255000,
            "time": "2026-02-05 07:00",
            "temp_c": 19.3,
            "temp_f": 66.7,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 4.7,
            "wind_kph": 7.6,
            "wind_degree": 83,
            "wind_dir": "E",
            "pressure_mb": 1017,
            "pressure_in": 30.03,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 43,
            "cloud": 6,
            "feelslike_c": 19.3,
            "feelslike_f": 66.7,
            "windchill_c": 19.3,
            "windchill_f": 66.7,
            "heatindex_c": 19.3,
            "heatindex_f": 66.7,
            "dewpoint_c": 6.5,
            "dewpoint_f": 43.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.9,
            "gust_kph": 15.9,
            "uv": 0.2,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1770258600,
            "time": "2026-02-05 08:00",
            "temp_c": 22.5,
            "temp_f": 72.5,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 6.3,
            "wind_kph": 10.1,
            "wind_degree": 93,
            "wind_dir": "E",
            "pressure_mb": 1018,
            "pressure_in": 30.06,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 39,
            "cloud": 4,
            "feelslike_c": 24.1,
            "feelslike_f": 75.4,
            "windchill_c": 22.5,
            "windchill_f": 72.5,
            "heatindex_c": 24.1,
            "heatindex_f": 75.4,
            "dewpoint_c": 8,
            "dewpoint_f": 46.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 7.9,
            "gust_kph": 12.7,
            "uv": 1,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1770262200,
            "time": "2026-02-05 09:00",
            "temp_c": 24.9,
            "temp_f": 76.8,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 9.8,
            "wind_kph": 15.8,
            "wind_degree": 114,
            "wind_dir": "ESE",
            "pressure_mb": 1018,
            "pressure_in": 30.07,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 39,
            "cloud": 4,
            "feelslike_c": 25.3,
            "feelslike_f": 77.5,
            "windchill_c": 24.9,
            "windchill_f": 76.8,
            "heatindex_c": 25.3,
            "heatindex_f": 77.5,
            "dewpoint_c": 10,
            "dewpoint_f": 50.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.3,
            "gust_kph": 18.2,
            "uv": 2.8,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1770265800,
            "time": "2026-02-05 10:00",
            "temp_c": 27.1,
            "temp_f": 80.7,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 12.8,
            "wind_kph": 20.5,
            "wind_degree": 124,
            "wind_dir": "SE",
            "pressure_mb": 1018,
            "pressure_in": 30.07,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 37,
            "cloud": 3,
            "feelslike_c": 26.7,
            "feelslike_f": 80.1,
            "windchill_c": 27.1,
            "windchill_f": 80.7,
            "heatindex_c": 26.7,
            "heatindex_f": 80.1,
            "dewpoint_c": 11.1,
            "dewpoint_f": 51.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 14.7,
            "gust_kph": 23.6,
            "uv": 5.2,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1770269400,
            "time": "2026-02-05 11:00",
            "temp_c": 28.6,
            "temp_f": 83.5,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 12.5,
            "wind_kph": 20.2,
            "wind_degree": 124,
            "wind_dir": "SE",
            "pressure_mb": 1017,
            "pressure_in": 30.04,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 33,
            "cloud": 6,
            "feelslike_c": 27.8,
            "feelslike_f": 82,
            "windchill_c": 28.6,
            "windchill_f": 83.5,
            "heatindex_c": 27.8,
            "heatindex_f": 82,
            "dewpoint_c": 10.8,
            "dewpoint_f": 51.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 14.4,
            "gust_kph": 23.2,
            "uv": 7.3,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1770273000,
            "time": "2026-02-05 12:00",
            "temp_c": 29.7,
            "temp_f": 85.5,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 9.8,
            "wind_kph": 15.8,
            "wind_degree": 122,
            "wind_dir": "ESE",
            "pressure_mb": 1016,
            "pressure_in": 30,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 29,
            "cloud": 4,
            "feelslike_c": 28.4,
            "feelslike_f": 83.2,
            "windchill_c": 29.7,
            "windchill_f": 85.5,
            "heatindex_c": 28.4,
            "heatindex_f": 83.2,
            "dewpoint_c": 9.6,
            "dewpoint_f": 49.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.3,
            "gust_kph": 18.2,
            "uv": 8.1,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1770276600,
            "time": "2026-02-05 13:00",
            "temp_c": 30.3,
            "temp_f": 86.5,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 7.8,
            "wind_kph": 12.6,
            "wind_degree": 115,
            "wind_dir": "ESE",
            "pressure_mb": 1015,
            "pressure_in": 29.96,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 26,
            "cloud": 22,
            "feelslike_c": 28.7,
            "feelslike_f": 83.6,
            "windchill_c": 30.3,
            "windchill_f": 86.5,
            "heatindex_c": 28.7,
            "heatindex_f": 83.6,
            "dewpoint_c": 8.5,
            "dewpoint_f": 47.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9,
            "gust_kph": 14.5,
            "uv": 7.5,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1770280200,
            "time": "2026-02-05 14:00",
            "temp_c": 30.6,
            "temp_f": 87.1,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 6.3,
            "wind_kph": 10.1,
            "wind_degree": 104,
            "wind_dir": "ESE",
            "pressure_mb": 1013,
            "pressure_in": 29.93,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 24,
            "cloud": 18,
            "feelslike_c": 28.8,
            "feelslike_f": 83.9,
            "windchill_c": 30.6,
            "windchill_f": 87.1,
            "heatindex_c": 28.8,
            "heatindex_f": 83.9,
            "dewpoint_c": 7.7,
            "dewpoint_f": 45.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 7.2,
            "gust_kph": 11.6,
            "uv": 5.5,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1770283800,
            "time": "2026-02-05 15:00",
            "temp_c": 30.8,
            "temp_f": 87.5,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 5.8,
            "wind_kph": 9.4,
            "wind_degree": 91,
            "wind_dir": "E",
            "pressure_mb": 1013,
            "pressure_in": 29.91,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 23,
            "cloud": 16,
            "feelslike_c": 29,
            "feelslike_f": 84.1,
            "windchill_c": 30.9,
            "windchill_f": 87.5,
            "heatindex_c": 29,
            "heatindex_f": 84.1,
            "dewpoint_c": 7.3,
            "dewpoint_f": 45.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6.7,
            "gust_kph": 10.8,
            "uv": 3.1,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1770287400,
            "time": "2026-02-05 16:00",
            "temp_c": 30.9,
            "temp_f": 87.6,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 6,
            "wind_kph": 9.7,
            "wind_degree": 80,
            "wind_dir": "E",
            "pressure_mb": 1013,
            "pressure_in": 29.91,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 22,
            "cloud": 14,
            "feelslike_c": 28.9,
            "feelslike_f": 84.1,
            "windchill_c": 30.9,
            "windchill_f": 87.6,
            "heatindex_c": 28.9,
            "heatindex_f": 84.1,
            "dewpoint_c": 7,
            "dewpoint_f": 44.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 7,
            "gust_kph": 11.2,
            "uv": 1.2,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1770291000,
            "time": "2026-02-05 17:00",
            "temp_c": 30.4,
            "temp_f": 86.7,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 7.4,
            "wind_kph": 11.9,
            "wind_degree": 75,
            "wind_dir": "ENE",
            "pressure_mb": 1013,
            "pressure_in": 29.92,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 23,
            "cloud": 14,
            "feelslike_c": 28.5,
            "feelslike_f": 83.2,
            "windchill_c": 30.4,
            "windchill_f": 86.6,
            "heatindex_c": 28.5,
            "heatindex_f": 83.2,
            "dewpoint_c": 7,
            "dewpoint_f": 44.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.5,
            "gust_kph": 13.7,
            "uv": 0.2,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1770294600,
            "time": "2026-02-05 18:00",
            "temp_c": 26.9,
            "temp_f": 80.4,
            "is_day": 0,
            "condition": {
              "text": "Clear ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 6.5,
            "wind_kph": 10.4,
            "wind_degree": 68,
            "wind_dir": "ENE",
            "pressure_mb": 1014,
            "pressure_in": 29.95,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 28,
            "cloud": 14,
            "feelslike_c": 25.9,
            "feelslike_f": 78.5,
            "windchill_c": 26.9,
            "windchill_f": 80.4,
            "heatindex_c": 25.9,
            "heatindex_f": 78.5,
            "dewpoint_c": 6.7,
            "dewpoint_f": 44.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 12.7,
            "gust_kph": 20.4,
            "uv": 0,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1770298200,
            "time": "2026-02-05 19:00",
            "temp_c": 25.1,
            "temp_f": 77.2,
            "is_day": 0,
            "condition": {
              "text": "Clear ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 4,
            "wind_kph": 6.5,
            "wind_degree": 74,
            "wind_dir": "ENE",
            "pressure_mb": 1015,
            "pressure_in": 29.99,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 30,
            "cloud": 13,
            "feelslike_c": 24.8,
            "feelslike_f": 76.6,
            "windchill_c": 25.1,
            "windchill_f": 77.2,
            "heatindex_c": 24.8,
            "heatindex_f": 76.6,
            "dewpoint_c": 6.4,
            "dewpoint_f": 43.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.5,
            "gust_kph": 13.6,
            "uv": 0,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1770301800,
            "time": "2026-02-05 20:00",
            "temp_c": 24.6,
            "temp_f": 76.3,
            "is_day": 0,
            "condition": {
              "text": "Clear ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 1.3,
            "wind_kph": 2.2,
            "wind_degree": 109,
            "wind_dir": "ESE",
            "pressure_mb": 1017,
            "pressure_in": 30.02,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 32,
            "cloud": 15,
            "feelslike_c": 24.6,
            "feelslike_f": 76.3,
            "windchill_c": 24.6,
            "windchill_f": 76.4,
            "heatindex_c": 24.6,
            "heatindex_f": 76.3,
            "dewpoint_c": 6.7,
            "dewpoint_f": 44.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 2.8,
            "gust_kph": 4.5,
            "uv": 0,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1770305400,
            "time": "2026-02-05 21:00",
            "temp_c": 24.4,
            "temp_f": 76,
            "is_day": 0,
            "condition": {
              "text": "Clear ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 0.9,
            "wind_kph": 1.4,
            "wind_degree": 229,
            "wind_dir": "SW",
            "pressure_mb": 1017,
            "pressure_in": 30.03,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 33,
            "cloud": 14,
            "feelslike_c": 24.6,
            "feelslike_f": 76.3,
            "windchill_c": 24.4,
            "windchill_f": 76,
            "heatindex_c": 24.6,
            "heatindex_f": 76.3,
            "dewpoint_c": 7.2,
            "dewpoint_f": 44.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 1.8,
            "gust_kph": 3,
            "uv": 0,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1770309000,
            "time": "2026-02-05 22:00",
            "temp_c": 25,
            "temp_f": 77,
            "is_day": 0,
            "condition": {
              "text": "Clear ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.6,
            "wind_kph": 5.8,
            "wind_degree": 300,
            "wind_dir": "WNW",
            "pressure_mb": 1017,
            "pressure_in": 30.04,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 33,
            "cloud": 15,
            "feelslike_c": 24.9,
            "feelslike_f": 76.9,
            "windchill_c": 25,
            "windchill_f": 77,
            "heatindex_c": 24.9,
            "heatindex_f": 76.9,
            "dewpoint_c": 7.6,
            "dewpoint_f": 45.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6.2,
            "gust_kph": 10,
            "uv": 0,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          },
          {
            "time_epoch": 1770312600,
            "time": "2026-02-05 23:00",
            "temp_c": 24.7,
            "temp_f": 76.5,
            "is_day": 0,
            "condition": {
              "text": "Clear ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 4.5,
            "wind_kph": 7.2,
            "wind_degree": 331,
            "wind_dir": "NNW",
            "pressure_mb": 1017,
            "pressure_in": 30.03,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 33,
            "cloud": 15,
            "feelslike_c": 24.8,
            "feelslike_f": 76.6,
            "windchill_c": 24.7,
            "windchill_f": 76.5,
            "heatindex_c": 24.8,
            "heatindex_f": 76.6,
            "dewpoint_c": 7.5,
            "dewpoint_f": 45.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 7.5,
            "gust_kph": 12,
            "uv": 0,
            "short_rad": 0,
            "diff_rad": 0,
            "dni": 0,
            "gti": 0
          }
        ]
      }
    ]
  }
}


console.log(weatherAPI.forecast.forecastday[0].day.maxtemp_c)